apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-custom
  resources:
    requests:
      storage: 10Gi
