kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-custom
provisioner: kubernetes.io/Azure-disk
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
